/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer3
 */
public class AplikasiPenghitungHari extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPenghitungHari
     */
    public AplikasiPenghitungHari() {
        initComponents();
        setupEventListeners();
        
        spinnerTahun.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                
                sinkronkanSpinnerKeCalendar(); 
            }
        });
        
        comboBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Panggil metode sinkronisasi yang SAMA
                sinkronkanInputKeCalendar();
            }
        });
    }
    
    private void sinkronkanSpinnerKeCalendar() {
        try {
            int tahun = (Integer) spinnerTahun.getValue();
            int bulanIndex = comboBulan.getSelectedIndex() + 1;
            
            java.time.LocalDate tanggalDariInput = java.time.LocalDate.of(tahun, bulanIndex, 1);
            
            
            java.util.Date date = java.sql.Date.valueOf(tanggalDariInput);
            jCalendar1.setDate(date);
            
        } catch (Exception e) {
            
        }
    }
    
    
    private void sinkronkanInputKeCalendar() {
        try {
            
            int tahun = (Integer) spinnerTahun.getValue();
            
            
            
            int bulanIndex = comboBulan.getSelectedIndex() + 1; 
            
            
            java.time.LocalDate tanggalDariInput = java.time.LocalDate.of(tahun, bulanIndex, 1);
            
            
            java.util.Date date = java.sql.Date.valueOf(tanggalDariInput);
            
            
            jCalendar1.setDate(date);
            
        } catch (Exception e) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        comboBulan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lblBulan = new javax.swing.JLabel();
        lblTahun = new javax.swing.JLabel();
        spinnerTahun = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblHasil = new javax.swing.JLabel();
        lblHariPertama = new javax.swing.JLabel();
        lblHariTerakhir = new javax.swing.JLabel();
        lblKabisat = new javax.swing.JLabel();
        lblSelisihHari = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni ", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Aplikasi Penghitung Hari");

        lblBulan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblBulan.setText("Bulan");

        lblTahun.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTahun.setText("Tahun");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Calender :");

        btnHitung.setText("Hitung Hari");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        jButton3.setText("Clear");

        lblHasil.setText("Jumlah hari:");

        lblHariPertama.setText("Hari Pertama:");

        lblHariTerakhir.setText("Hari Terakhir:");

        lblKabisat.setText("Status");

        lblSelisihHari.setText("Selisih Hari");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTahun)
                                .addGap(53, 53, 53)
                                .addComponent(spinnerTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblBulan)
                                .addGap(58, 58, 58)
                                .addComponent(comboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                                    .addComponent(jCalendar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(237, 237, 237)
                                        .addComponent(btnHitung)
                                        .addGap(29, 29, 29)
                                        .addComponent(jButton3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(251, 251, 251)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblHasil)
                                            .addComponent(lblHariPertama)
                                            .addComponent(lblHariTerakhir)
                                            .addComponent(lblKabisat)
                                            .addComponent(lblSelisihHari))))))))
                .addGap(205, 205, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBulan)
                    .addComponent(comboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTahun))
                .addGap(65, 65, 65)
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(lblHasil)
                        .addGap(18, 18, 18)
                        .addComponent(lblHariPertama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHariTerakhir)
                        .addGap(20, 20, 20)
                        .addComponent(lblKabisat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSelisihHari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHitung)
                            .addComponent(jButton3))
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
         try {
        
        int bulanIndex = comboBulan.getSelectedIndex() + 1;
        int tahun = (Integer) spinnerTahun.getValue();

        
        if (bulanIndex < 1 || bulanIndex > 12) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Pilih bulan yang valid!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        java.time.LocalDate tanggalDariCombo = java.time.LocalDate.of(tahun, bulanIndex, 1);
        
        
        java.util.Date selectedDate1 = jCalendar1.getDate();
        java.time.LocalDate tanggalDariCalendar1 = null;
        
        if (selectedDate1 != null) {
            
            tanggalDariCalendar1 = selectedDate1.toInstant()
                .atZone(java.time.ZoneId.systemDefault())
                .toLocalDate();
        }

        
        java.time.LocalDate tanggalUntukPerhitungan;
        
        if (tanggalDariCalendar1 != null) {
            
            tanggalUntukPerhitungan = tanggalDariCalendar1;
            
            
            int bulanCalendar = tanggalDariCalendar1.getMonthValue();
            int tahunCalendar = tanggalDariCalendar1.getYear();
            
            comboBulan.setSelectedIndex(bulanCalendar - 1);
            spinnerTahun.setValue(tahunCalendar);
        } else {
            
            tanggalUntukPerhitungan = tanggalDariCombo;
            
            
            java.util.Date date = java.sql.Date.valueOf(tanggalDariCombo);
            jCalendar1.setDate(date);
        }

        
        int jumlahHari = tanggalUntukPerhitungan.lengthOfMonth();
        
        
        String hariPertama = tanggalUntukPerhitungan.getDayOfWeek().getDisplayName(
            java.time.format.TextStyle.FULL, new java.util.Locale("id", "ID"));
        
        java.time.LocalDate tanggalTerakhir = tanggalUntukPerhitungan.withDayOfMonth(jumlahHari);
        String hariTerakhir = tanggalTerakhir.getDayOfWeek().getDisplayName(
            java.time.format.TextStyle.FULL, new java.util.Locale("id", "ID"));
        
        
        boolean isKabisat = tanggalUntukPerhitungan.isLeapYear();
        String statusKabisat = isKabisat ? "Tahun Kabisat" : "Bukan Tahun Kabisat";

        
        long selisihHari = 0;
        java.util.Date selectedDate2 = jCalendar2.getDate();
        
        if (selectedDate1 != null && selectedDate2 != null) {
            java.time.LocalDate tanggalCalendar2 = selectedDate2.toInstant()
                .atZone(java.time.ZoneId.systemDefault())
                .toLocalDate();
            
            if (!tanggalCalendar2.isBefore(tanggalDariCalendar1)) {
                selisihHari = java.time.temporal.ChronoUnit.DAYS.between(tanggalDariCalendar1, tanggalCalendar2);
            }
        }

        
        lblHasil.setText("Jumlah hari: " + jumlahHari);
        lblHariPertama.setText("Hari pertama: " + hariPertama);
        lblHariTerakhir.setText("Hari terakhir: " + hariTerakhir);
        lblKabisat.setText("tahun: " + statusKabisat);
        lblSelisihHari.setText("Selisih hari: " + selisihHari + " hari");

    } catch (Exception ex) {
        ex.printStackTrace(); 
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Terjadi kesalahan: " + ex.getMessage(), 
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnHitungActionPerformed
    private void setupEventListeners() {
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPenghitungHari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JComboBox<String> comboBulan;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBulan;
    private javax.swing.JLabel lblHariPertama;
    private javax.swing.JLabel lblHariTerakhir;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblKabisat;
    private javax.swing.JLabel lblSelisihHari;
    private javax.swing.JLabel lblTahun;
    private javax.swing.JSpinner spinnerTahun;
    // End of variables declaration//GEN-END:variables
}
